# Agentic OS Configuration Example
# Copy this file to $HOME/.agent-os/config.yaml and customize as needed

# WebUI configuration
webui:
  port: 3000  # Port for the WebUI server
  cors:
    origin: "*"  # CORS origin (use "*" for development, specific domain for production)
    credentials: false  # Allow credentials in CORS requests

# AgenticOS configuration
agentic:
  # Model configuration
  model:
    providers:
      openai:
        endpoint: "https://api.openai.com/v1"
        apiKey: "${OPENAI_API_KEY}"  # API key (use environment variable)
        adapterType: "openai"
        models:
          - type: "llm"
            name: "gpt-4"
          - type: "llm"
            name: "gpt-3.5-turbo"
          - type: "embed"
            name: "text-embedding-ada-002"

  # Task configuration
  task:
    maxConcurrentTasks: 5  # Maximum concurrent tasks
    taskTimeout: 300000  # Task timeout in milliseconds (5 minutes)

  # Ledger configuration
  ledger:
    persistence: true  # Enable persistence
    maxEntries: 1000  # Maximum ledger entries to keep
