# Agentic OS CLI Configuration Example
# Copy this file to ~/.agentic-os/config.yaml and customize as needed

model:
  # Model providers configuration
  providers:
    # OpenAI provider
    openai-main:
      endpoint: https://api.openai.com/v1
      # You can set API key here or use environment variable OPENAI_API_KEY
      apiKey: ${OPENAI_API_KEY}
      adapterType: openai
      models:
        - type: llm
          name: gpt-4-turbo-preview
        - type: llm
          name: gpt-3.5-turbo
        - type: embed
          name: text-embedding-3-small

    # Example: Add more providers if needed
    # anthropic-main:
    #   endpoint: https://api.anthropic.com/v1
    #   apiKey: ${ANTHROPIC_API_KEY}
    #   adapterType: anthropic
    #   models:
    #     - type: llm
    #       name: claude-3-opus-20240229
